config/routes.rb
Rails.application.routes.draw do

  resources :folders do
    get :ask_delete, on: :member
    post :organize, on: :collection
    post :save_sort, on: :collection
    post :toggle_collapse, on: :collection
  end

  resources :projects do
    get :ask_delete, on: :member
    get :organize, on: :collection
    post :toggle_folder, on: :collection
    post :checkall_folder, on: :collection
    post :assigned_folder, on: :collection

    resources :forms, except: [:new] do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
    resources :surveys, except: [:new] do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :forms, only: [] do
    resources :pages do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :pages, only: [] do
    resources :sections do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :sections, only: [] do
    resources :fields do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :fields, only: [] do
    resources :field_opts do
      get :ask_delete, on: :member
      post :save_sort, on: :collection      
    end
  end

  resources :records
  resources :users

  get  'login'  => 'sessions#new'
  post 'login'  => 'sessions#create'
  get  'logout' => 'sessions#destroy'

  get 'about'   => 'home#about'
  get 'contact' => 'home#contact'

  root 'home#index'

end

app/views/shared/_flash.html.haml
- if flash[:notice]
  :javascript
    doModal('noticeModal', 'Notice', "<p>#{flash[:notice]}</p>", 'Close', 'primary')
  - flash[:notice] = nil
- if flash[:error]
  :javascript
    doModal('errorModal', 'Error', "<p>#{flash[:error]}</p>", 'Close', 'primary')
  - flash[:error] = nil

app/views/shared/_menu.html.haml
.navbar-wrapper
  .container
    %nav.navbar.navbar-inverse.navbar-fixed-top
      = link_to image_tag('/favicon.png', class: 'navbar-left navbar-logo hidden-xs', title: '', alt: ''), logged_in? ? projects_path : root_path
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{ 'aria-controls' => :navbar, 'aria-expanded' => false, 'data-target' => '#navbar', 'data-toggle' => :collapse, type: :button }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to SITE_TITLE, logged_in? ? projects_path : root_path, class: 'navbar-brand'
        .navbar-collapse.collapse#navbar
          %ul.nav.navbar-nav.navbar-right
            %li{ class: active_menu('/') }
              = link_to raw("#{sg 'home'} &nbsp;Home"), logged_in? ? projects_path : root_path
            %li{ class: active_menu('/about') }
              = link_to(raw('<span class="glyphicon glyphicon-info-sign"></span>&nbsp; About'), about_path)
            %li{ class: active_menu('/contact') }
              = link_to(raw('<span class="glyphicon glyphicon-globe"></span>&nbsp; Contact'), contact_path)
            - if logged_in?
              %li
                = link_to(raw('<span class="glyphicon glyphicon-log-out"></span>&nbsp; Logout'), logout_path)
            - unless logged_in?
              %li{ class: active_menu('/users/new') }
                = link_to raw("#{sg 'plus-sign'} &nbsp;Signup"), new_user_path
              %li{ class: active_menu('/login') }
                = link_to raw("#{sg 'log-in'} &nbsp;Login"), login_path

app/views/shared/_sidebar.html.haml
%ul.nav.nav-sidebar
  - %w(projects records).each do |m|
    %li{ class: ('active' if request.original_fullpath.include?(m)) }
      - title = "<span class='glyphicon glyphicon-#{glyph(m)}'> #{m.titleize}".html_safe
      = link_to title, send("#{m}_path")