config/routes.rb
Rails.application.routes.draw do

  resources :folders do
    get :ask_delete, on: :member
    post :organize, on: :collection
    post :save_sort, on: :collection
    post :toggle_collapse, on: :collection
  end

  resources :projects do
    get :ask_delete, on: :member
    get :organize, on: :collection
    post :toggle_folder, on: :collection
    post :checkall_folder, on: :collection
    post :assigned_folder, on: :collection

    resources :forms, except: [:new] do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
    resources :surveys, except: [:new] do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :forms, only: [] do
    resources :pages do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :pages, only: [] do
    resources :sections do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :sections, only: [] do
    resources :fields do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :fields, only: [] do
    resources :field_opts do
      get :ask_delete, on: :member
      post :save_sort, on: :collection      
    end
  end

  resources :records
  resources :users

  get  'login'  => 'sessions#new'
  post 'login'  => 'sessions#create'
  get  'logout' => 'sessions#destroy'

  get 'about'   => 'home#about'
  get 'contact' => 'home#contact'

  root 'home#index'

end

app/models/section.rb
class Section < ActiveRecord::Base

  belongs_to :page
  acts_as_list scope: :page

  has_many :fields, -> { order :position }, dependent: :destroy

  validates :page_id, presence: true
  validates :name, presence: true, length: { maximum: 64 }, uniqueness: { scope: :page_id }

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  before_action :require_login
  before_action :get_page
  before_action only: [:ask_delete, :destroy, :edit, :update] { get_section( params[:id] ) }

  layout 'main'

  def create
    @section = Section.create(section_params.merge(page: @page))
    if @section.valid?
      redirect_to edit_form_page_path(@page.form, @page)
      return
    end
    render 'pages/edit'
  end

  def edit
    @fields = @section.fields
    @field = Field.new
    @form = @section.page.form
    @field_types = FieldType.all
  end

  def update
    @section.update(section_params)
    if @section.valid?
      redirect_to edit_page_section_path(@page, @section)
      return
    end
    @fields = @section.fields
    @field = Field.new
    @form = @section.page.form
    render 'sections/edit'
  end
  
  def ask_delete
  end

  def destroy
    @id = @section.id
    @section.destroy
  end

  def save_sort
    save_sorted(@page.sections)
    head :ok
  end

  private

  def section_params
    params.require(:section).permit(:name)
  end

  def get_page
    @page = Page.where(id: params[:page_id]).first
    @project = @current_user.projects.where(id: @page.form.project_id).first if @page
    @page = nil unless @project
    redirect_to root_path unless @page
  end

end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_ask_delete.html.haml
.modal.fade{ id: "adm_#{@section.id}", role: :dialog, tabindex: -1 }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ 'aria-label' => 'Close', 'data-dismiss' => :modal, type: :button }
          %span{ 'aria-hidden' => :true } &#215;
        %h4.modal-title Confirm Section Delete
      .modal-body
        %p Are you sure you want to delete the #{@section.name} section?
      .modal-footer
        %button.btn.btn-default{ 'data-dismiss' => :modal, type: :button } #{sg 'remove'} &nbsp;Close
        %button.btn.btn-danger{ id: :delete, type: :button } #{sg 'share-alt'} &nbsp;Delete
:javascript
  $(function(){ $('#delete').on( 'click', function() {
    $.ajax({
      method: 'delete',
      url: "/pages/#{@page.id}/sections/#{@section.id}"
    });
  }); });

app/views/sections/_fields.html.haml
%h4 Section Fields

- unless @section.fields.count.zero?
  %table.table.table-condensed.table-hover.table-bordered.table-striped#sort_fields
    %thead
      %tr
        %th Field
        %th Type
        %th{ colspan: 2 } &nbsp;
    %tbody
      - @section.fields.each do |f|
        %tr.hand{ id: "s_#{f.id}" }
          %td.middle= " &nbsp;#{sg 'sort'} &nbsp;#{f.name}".html_safe
          %td.middle= f.field_type
          %td.tight= link_to "#{sg 'pencil'} &nbsp;Edit".html_safe, edit_section_field_path(@section, f), id: "field_#{f.id}", type: :button, class: 'btn btn-sm btn-warning'
          %td.tight= link_to "#{sg 'remove'} &nbsp;Delete".html_safe, 'javascript:;', id: "ad_field_#{f.id}", type: :button, class: 'btn btn-sm btn-danger'

%div
  .panel.panel-default
    .panel-body
      = simple_form_for [@section, @field] do |f|
        = f.hidden_field :section_id, value: @section.id
        = render partial: 'fields/form', locals: { f: f }
        = f.button :button, class: 'btn-success' do
          = sg 'share-alt'
          Create Field

app/views/sections/ask_delete.js.erb
<% if @section -%>
$('body').append("<%= escape_javascript( render( partial: 'sections/ask_delete', locals: { section: @section } ) ) %>");
$('#adm_<%= @section.id %>').modal();
<% end -%>

app/views/sections/edit.html.haml
.h3.page-header.hidden-xs
  = link_to 'Projects', projects_path
  = dl
  = link_to @project.name, edit_project_path(@project)
  = dl
  = link_to @section.page.form.name, edit_project_form_path(@section.page.form.project, @section.page.form)
  = dl
  = link_to @section.page.name, edit_form_page_path(@section.page.form, @section.page)
  = dl
  Edit Section

%div
  .row
    .col-md-6
      %div
        .panel.panel-default
          .panel-body
            = simple_form_for [@section.page, @section], method: :put do |f|
              = render partial: 'sections/form', locals: { f: f }
              .form-group
                = f.button :button, class: 'btn-success' do
                  = sg 'pencil'
                  Update Section
  .row
    .col-md-6
      = render 'sections/fields'