config/routes.rb
Rails.application.routes.draw do

  resources :folders do
    get :ask_delete, on: :member
    post :organize, on: :collection
    post :save_sort, on: :collection
    post :toggle_collapse, on: :collection
  end

  resources :projects do
    get :ask_delete, on: :member
    get :organize, on: :collection
    post :toggle_folder, on: :collection
    post :checkall_folder, on: :collection
    post :assigned_folder, on: :collection

    resources :forms, except: [:new] do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
    resources :surveys, except: [:new] do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :forms, only: [] do
    resources :pages do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :pages, only: [] do
    resources :sections do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :sections, only: [] do
    resources :fields do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :fields, only: [] do
    resources :field_opts do
      get :ask_delete, on: :member
      post :save_sort, on: :collection      
    end
  end

  resources :records
  resources :users

  get  'login'  => 'sessions#new'
  post 'login'  => 'sessions#create'
  get  'logout' => 'sessions#destroy'

  get 'about'   => 'home#about'
  get 'contact' => 'home#contact'

  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :surveys, -> { order :position }, dependent: :destroy
  has_many :forms, -> { order :position }, dependent: :destroy

  has_many :project_folders, dependent: :destroy

  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects

  validates :name, presence: true, length: { maximum: 64 }

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :require_login

  layout 'main'

  def index
    if @current_user.project_folders.count.zero?
      @projects = @current_user.undeleted_projects
    else
      @unfoldered_projects = @current_user.unfoldered_projects
      @folders = @current_user.folders
    end
    @projects_count = @current_user.undeleted_projects.count
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    if @project.valid?
      UserProject.create!(:user => @current_user, :project => @project, :relationship => Relationship.owner)
      redirect_to edit_project_path(@project)
      return
    end
    render :new
    return
  end

  def edit
    @project = project_by_id params[:id]
    unless @project && @current_user.is_owner?(@project)
      flash[:notice] = 'Project not found'
      redirect_to projects_path
      return
    end
    @surveys = @project.surveys
    @survey = Survey.new
    @forms = @project.forms
    @form = Form.new
  end

  def update
    @project = project_by_id params[:id]
    unless @project && @current_user.is_owner?(@project)
      flash[:notice] = 'Project not found'
      redirect_to projects_path
      return
    end
    @project.update(project_params)
    if @project.valid?
      redirect_to edit_project_path
      return
    end
    flash[:notice] = 'Project update failed'
    render :edit
    return
  end

  def ask_delete
    @project = project_by_id params[:id]
    unless @project && @current_user.is_owner?(@project)
      flash[:notice] = 'Project not found'
      redirect_to projects_path
      return
    end
  end

  def destroy
    @project = project_by_id params[:id]
    if @project && @current_user.is_owner?(@project)
      name = @project.name
      @project.deleted = true
      @project.save
      @project.project_folders.destroy_all
      flash[:notice] = "Project #{name} deleted"
    else
      flash[:notice] = 'Project not found'
    end
    redirect_to projects_path
    return
  end

  def organize
    @projects = @current_user.undeleted_projects
    @folders = @current_user.folders
    @folder = Folder.new
  end

  def assigned_folder
    session[:organize_assigned] = params[:assigned].to_i
    get_projects_list
    render :partial => 'folders/projects_list'
    return
  end

  def checkall_folder
    if params[:project_ids]
      @folder = @current_user.folders.where(:id => params[:folder_id].to_i).first
      unless @folder.nil?
        params[:project_ids].collect{ |id| id.to_i }.each do |id|
          @project_folder = @current_user.project_folders.where(:folder => @folder, :project_id => id).first
          if params[:checkall].to_i == 1
            ProjectFolder.create!(:user => @current_user,
                                  :project_id => id,
                                  :folder => @folder) unless @project_folder
          else
            @project_folder.destroy if @project_folder
          end
        end
      end
    end
    head :ok
  end

  def toggle_folder
    @folder = @current_user.folders.where(:id => params[:folder_id].to_i).first
    unless @folder.nil?
      params[:project_ids].collect{|id|id}.each do |id|
        @project_folder = @current_user.project_folders.where(:folder => @folder, :project_id => id).first
        if @project_folder
          @project_folder.destroy
        else
          ProjectFolder.create!(:user => @current_user,
                                :project_id => id,
                                :folder => @folder)
        end
      end
    end
    head :ok
  end

  private

  def project_by_id(id)
    @current_user.undeleted_projects.find{|p|p.id == id.to_i}
  end

  def project_params
    params.require(:project).permit(:name)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_edit_forms.html.haml
.row.hidden#forms
  %p &nbsp;
  - unless @project.forms.count.zero?
    %table.table.table-condensed.table-hover.table-bordered.table-striped#sort_forms
      %thead
        %tr
          %th Form
          %th Records
          %th{ colspan: 2 } &nbsp;
      %tbody
        - @project.forms.each do |f|
          %tr.hand{ id: "f_#{f.id}" }
            %td.middle #{ " &nbsp;#{sg 'sort'} &nbsp;#{f.name}".html_safe }
            %td.middle= f.records.size
            %td.tight= link_to raw("#{sg 'pencil'} &nbsp;Edit"), edit_project_form_path(@project, f), id: "form_#{f.id}", type: :button, class: 'btn btn-sm btn-warning'
            %td.tight= link_to raw("#{sg 'remove'} &nbsp;Delete"), 'javascript:;', id: "ad_form_#{f.id}", type: :button, class: 'btn btn-sm btn-danger'

  %div
    .panel.panel-default
      .panel-body
        = simple_form_for [@project, @form] do |f|
          = f.hidden_field :project_id, value: @project.id
          = render partial: 'forms/form', locals: { f: f }
          = f.button :button, class: 'btn-success' do
            = sg 'share-alt'
            Create New Form

app/views/projects/_edit_project.html.haml
.row.hidden#project
  %p &nbsp;
  .panel.panel-default
    .panel-body
      = simple_form_for @project, method: :put do |f|
        = render partial: 'projects/form', locals: { f: f }
        = f.button :button, class: 'btn-success' do
          = sg 'pencil'
          Update Project

app/views/projects/_edit_surveys.html.haml
.row.hidden#surveys
  %p &nbsp;
  - unless @project.surveys.count.zero?
    %table.table.table-condensed.table-hover.table-bordered.table-striped#sort_surveys
      %thead
        %tr
          %th Survey
          %th Records
          %th{ colspan: 2 } &nbsp;
      %tbody
        - @project.surveys.each do |s|
          %tr.hand{ id: "s_#{s.id}" }
            %td.middle #{ " &nbsp;#{sg 'sort'} &nbsp;#{s.name}".html_safe }
            %td.middle= s.records.size
            %td.tight= link_to raw("#{sg 'pencil'} &nbsp;Edit"), edit_project_survey_path(@project, s), id: "survey_#{s.id}", type: :button, class: 'btn btn-sm btn-warning'
            %td.tight= link_to raw("#{sg 'remove'} &nbsp;Delete"), 'javascript:;', id: "ad_survey_#{s.id}", type: :button, class: 'btn btn-sm btn-danger'

  %div
    .panel.panel-default
      .panel-body
        = simple_form_for [@project, @survey] do |f|
          = f.hidden_field :project_id, value: @project.id
          = render partial: 'projects/survey', locals: { f: f }
          = f.button :button, class: 'btn-success' do
            = sg 'share-alt'
            Create New Survey

app/views/projects/_folders.html.haml
%div
  .panel.panel-default
    .panel-body
      = form_for @folder, html: { class: 'form-inline' } do
        - if @folder.errors[:name].empty?
          .form-group
            %input.form-control#name{ name: :name, placeholder: 'Name', type: :text, value: @folder.name }
            %button.btn.btn-success{ type: :submit }
              #{sg 'share-alt'} Create New Folder
          %p
            &nbsp;
        - else
          .form-group.has-error.has-feedback
            %input.form-control#name{ 'aria-describedby' => 'nameErrorStatus', name: :name, placeholder: 'Name', type: :text, value: @folder.name }
            %span.glyphicon.glyphicon-remove.form-control-feedback{ 'aria-hidden' => true }
          \&#160;
          %button.btn.btn-success{ type: :submit }
            #{sg 'share-alt'} Create New Folder
          %span.sr-only#nameErrorStatus (error)
          %span.help-block= @folder.errors[:name].first
      - unless @folders.count.zero?
        %table.table.table-condensed.table-hover.table-bordered.table-striped#sort_folders
          %thead
            %tr
              %th{ colspan: 3 } Folder
          %tbody
            - @folders.each do |f|
              %tr.hand{ id: "f_#{f.id}" }
                %td.middle{ style: f.td_style }
                  = raw(" &nbsp;#{sg 'sort'} &nbsp;#{f.name}")
                %td.tight= link_to raw("#{sg 'pencil'} &nbsp;Edit"), 'javascript:;', id: "folder_#{f.id}", type: :button, class: 'btn btn-sm btn-warning'
                %td.tight= link_to raw("#{sg 'remove'} &nbsp;Delete"), 'javascript:;', id: "ad_folder_#{f.id}", type: :button, class: 'btn btn-sm btn-danger'

app/views/projects/_folders_list.html.haml
- unless @folders.count.zero?
  %table.table.table-condensed.table-hover.table-bordered.table-striped
    %thead
      %tr
        %th{ colspan: 4 } Project Folders
    %tbody
      - unless @unfoldered_projects.nil? || @unfoldered_projects.count.zero?
        %tr.lh32
          %td.middle{ colspan: 4 }
            &nbsp;
            %span.glyphicon.glyphicon-folder-open
              %b
                %a{ href: 'javascript:;', style: 'font-family: sans-serif; text-decoration: none; color: #000' }
                  Unfoldered
        %tr.sm-header
          %td.indent Project
          %td.tight Surveys
          %td.tight Forms
          %td &nbsp;
        - @unfoldered_projects.each do |p|
          - next if p.deleted
          %tr
            %td.middle.indent
              = p.name
            %td.center.middle
              = p.surveys.size
            %td.center.middle
              = p.forms.size
            %td.tight
              = link_to raw("#{sg 'pencil'} &nbsp;Edit"), edit_project_path(p), type: :button, class: 'btn btn-sm btn-warning'
              - if @current_user.is_owner?(p)
                = link_to raw("#{sg 'remove'} &nbsp;Delete"), ask_delete_project_path(p), type: :button, class: 'btn btn-sm btn-danger'

      - @folders.each do |f|
        - next if f.project_folders.count.zero?
        %tr.lh32
          %td.middle{ colspan: 4, style: f.td_style }
            %b
              &nbsp;
              - if f.collapsed
                %span.glyphicon.glyphicon-folder-close{ id: "fc-#{f.id}" }
                %span.glyphicon.glyphicon-folder-open{ id: "fo-#{f.id}", style: 'display:none' }
              - else
                %span.glyphicon.glyphicon-folder-close{ id: "fc-#{f.id}", style: 'display:none' }
                %span.glyphicon.glyphicon-folder-open{ id: "fo-#{f.id}" }
              &nbsp;
              %a{ href: 'javascript:;', onclick: "javascript:toggleFolderCollapse(#{f.id});", style: f.a_style }
                = f.name
        %tr.sm-header{ id: "header-#{f.id}", style: (f.collapsed ? 'display:none' : '').html_safe }
          %td.indent Project
          %td.tight Surveys
          %td.tight Forms
          %td &nbsp;
        - f.project_folders.each do |pf|
          - p = pf.project
          - next if p.deleted
          %tr{ id: "f#{f.id}-p#{p.id}", style: (f.collapsed ? 'display:none' : '').html_safe }
            %td.middle.indent{ style: f.td_style }
              = link_to p.name, edit_project_path(p), style: f.a_style
            %td.center.middle{ style: f.td_style }
              = p.surveys.size
            %td.center.middle{ style: f.td_style }
              = p.forms.size
            %td.tight
              = link_to raw("#{sg 'pencil'} &nbsp;Edit"), edit_project_path(p), type: :button, class: 'btn btn-sm btn-warning'
              - if @current_user.is_owner?(p)
                = link_to raw("#{sg 'remove'} &nbsp;Delete"), ask_delete_project_path(p), type: :button, class: 'btn btn-sm btn-danger'

app/views/projects/_projects.html.haml
%div
  .panel.panel-default
    .panel-body
      .form-group
        %label.control-label{ for: :folder }
          Choose Folder
        %select.form-control#folder_id{ name: :folder_id }
          %option{ value: 0 }
          - @folders.each do |f|
            - if f.id == session[:organize_folder_id]
              %option{ value: f.id, selected: :selected }
                = f.name
            - else
              %option{ value: f.id }
                = f.name
      #projects_list

:javascript
  $(function(){ getProjects() });

app/views/projects/_projects_list.html.haml
- unless @projects.count.zero?
  %table.table.table-condensed.table-hover.table-bordered.table-striped
    %thead
      %tr
        %th Projects
        %th &#160;
    %tbody
      - @projects.each do |p|
        %tr
          %td.middle= p.name
          %td
            = link_to raw("#{sg 'pencil'} &nbsp;Edit"), edit_project_path(p), type: :button, class: 'btn btn-sm btn-warning'
            - if @current_user.is_owner?(p)
              = link_to raw("#{sg 'remove'} &nbsp;Delete"), ask_delete_project_path(p), type: :button,
                        class: 'btn btn-sm btn-danger'

app/views/projects/_survey.html.haml
= f.input :name

app/views/projects/ask_delete.html.haml
%h3.page-header.hidden-xs
  = link_to 'Projects', projects_path
  = dl
  Delete Project
%div
  %p
    Are you sure you want to delete your project
    %b= @project.name
    ?
    %p &nbsp;
    = link_to raw("#{sg('remove')} &nbsp;Delete Project"), project_path(@project), method: :delete, type: :button,
              class: 'btn btn-sm btn-danger'

app/views/projects/edit.html.haml
.h3.page-header.hidden-xs
  = link_to 'Projects', projects_path
  = dl
  Edit Project

%ul.nav.nav-tabs
  %li#li_project{ role: :presentation }
    = link_to 'Project', 'javascript:;', id: :tab_project
  %li#li_forms{ role: :presentation }
    = link_to 'Forms', 'javascript:;', id: :tab_forms
  %li#li_surveys{ role: :presentation }
    = link_to 'Surveys', 'javascript:;', id: :tab_surveys

.col-md-6
  = render partial: 'projects/edit_project'
  = render partial: 'projects/edit_forms'
  = render partial: 'projects/edit_surveys'

app/views/projects/index.html.haml
%h3.page-header.hidden-xs Projects

%div
  .row
    .col-md-12
      %div
        .panel.panel-default
          .panel-body
            %p
              = link_to raw("#{sg 'plus'}&nbsp; New Project"), new_project_path, type: 'button', class: 'btn btn-success'
              - unless @projects_count.zero?
                = link_to raw("#{sg 'wrench'}&nbsp; Organize Projects"), organize_projects_path, type: 'button',
                          class: 'btn btn-info'
            - if @projects
              = render 'projects/projects_list'
            - elsif @folders
              = render 'projects/folders_list'

app/views/projects/new.html.haml
.h3.page-header.hidden-xs
  = link_to 'Projects', projects_path
  = dl
  New Project
.panel.panel-default
  .panel-heading
    .h3.panel-title Project Info
  .panel-body
    = form_for @project do
      = render 'projects/form'
      .form-group
        %button.btn.btn-success{ type: :submit }
          = sg('share-alt')
          &nbsp;Create Project

app/views/projects/organize.html.haml
%h3.page-header.hidden-xs
  = link_to 'Projects', projects_path
  = dl
  Organize Projects

%div
  .row
    .col-md-6
      = render 'projects/folders'
    .col-md-6
      - unless @folders.count.zero?
        = render 'projects/projects'

- if session[:show].present?
  - if session[:show] == 'edit_folder'
    :javascript
      $( function(){ editFolder(#{session[:id]}) } );
    - session[:show] = nil
    - session[:id] = nil