config/routes.rb
Rails.application.routes.draw do

  resources :folders do
    get :ask_delete, on: :member
    post :organize, on: :collection
    post :save_sort, on: :collection
    post :toggle_collapse, on: :collection
  end

  resources :projects do
    get :ask_delete, on: :member
    get :organize, on: :collection
    post :toggle_folder, on: :collection
    post :checkall_folder, on: :collection
    post :assigned_folder, on: :collection

    resources :forms, except: [:new] do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
    resources :surveys, except: [:new] do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :forms, only: [] do
    resources :pages do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :pages, only: [] do
    resources :sections do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :sections, only: [] do
    resources :fields do
      get :ask_delete, on: :member
      post :save_sort, on: :collection
    end
  end

  resources :fields, only: [] do
    resources :field_opts do
      get :ask_delete, on: :member
      post :save_sort, on: :collection      
    end
  end

  resources :records
  resources :users

  get  'login'  => 'sessions#new'
  post 'login'  => 'sessions#create'
  get  'logout' => 'sessions#destroy'

  get 'about'   => 'home#about'
  get 'contact' => 'home#contact'

  root 'home#index'

end

app/models/field.rb
class Field < ActiveRecord::Base

  belongs_to :field_type, counter_cache: true
  belongs_to :section, counter_cache: true
  acts_as_list scope: :section

  has_many :field_opts, -> { order :position }, dependent: :destroy

  validates :field_type_id, presence: true, numericality: { only_integer: true }
  validates :section_id, presence: true
  validates :name, presence: true, length: { maximum: 64 }, uniqueness: { scope: :section_id }

  validate :validate_field_type

  private

  def validate_field_type
    errors.add(:field_type_id, 'is invalid') unless FieldType.exists?(self.field_type_id)
  end
  
end

app/models/field_type.rb
class FieldType < ActiveRecord::Base

  has_many :fields, dependent: :destroy

  validates :name, presence: true, length: { maximum: 32 }, uniqueness: true

  scope :sorted, -> { order 'name' }

  def to_s
    name
  end
  
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController

  before_action :require_login
  before_action { get_section( params[:section_id] ) }
  before_action :get_field, only: [:ask_delete, :destroy, :edit, :update]
  
  layout 'main'

  def edit
    @field_types = FieldType.sorted
  end

  def update
    @field.update(field_params)
    if @field.valid?
      redirect_to edit_section_field_path(@section, @field)
      return
    end
    @field_types = FieldType.all
    render 'fields/edit'
  end
  
  def create
    @field = Field.create(field_params.merge(section: @section))
    if @field.valid?
      redirect_to edit_page_section_path(@section.page, @section)
      return
    end
    @field_types = FieldType.all
    render 'sections/edit'
  end

  def ask_delete
  end

  def destroy
    @id = @field.id
    @field.destroy
  end

  def save_sort
    save_sorted(@section.fields)
    head :ok
  end
  
  private

  def field_params
    params.require(:field).permit(:name, :field_type_id)
  end

  def get_field
    @field = Field.where(id: params[:id]).first
    @project = @current_user.projects.where(id: @field.section.page.form.project_id).first if @field
    @field = nil unless @project
    redirect_to root_path unless @field
  end
  
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_ask_delete.html.haml
.modal.fade{ id: "adm_#{@field.id}", role: :dialog, tabindex: -1 }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ 'aria-label' => 'Close', 'data-dismiss' => :modal, type: :button }
          %span{ 'aria-hidden' => :true } &#215;
        %h4.modal-title Confirm Field Delete
      .modal-body
        %p Are you sure you want to delete the #{@field.name} field?
      .modal-footer
        %button.btn.btn-default{ 'data-dismiss' => :modal, type: :button } #{sg 'remove'} &nbsp;Close
        %button.btn.btn-danger{ id: :delete, type: :button } #{sg 'share-alt'} &nbsp;Delete
:javascript
  $(function(){ $('#delete').on( 'click', function() {
    $.ajax({
      method: 'delete',
      url: "/sections/#{@section.id}/fields/#{@field.id}"
    });
  }); });

app/views/fields/_form.html.haml
= f.input :name
= f.input :field_type_id, collection: @field_types

app/views/fields/ask_delete.js.erb
<% if @field -%>
$('body').append("<%= escape_javascript( render( partial: 'fields/ask_delete', locals: { field: @field } ) ) %>");
$('#adm_<%= @field.id %>').modal();
<% end -%>

app/views/fields/edit.html.haml
.h3.page-header.hidden-xs
  = link_to 'Projects', projects_path
  = dl
  = link_to @field.section.page.form.project.name, edit_project_path(@field.section.page.form.project)
  = dl
  = link_to @field.section.page.form.name, edit_project_form_path(@field.section.page.form.project, @field.section.page.form)
  = dl
  = link_to @field.section.page.name, edit_form_page_path(@field.section.page.form, @field.section.page)
  = dl
  = link_to @field.section.name, edit_page_section_path(@field.section.page, @field.section.page)
  = dl
  Edit Field

%div
  .row
    .col-md-6
      %div
        .panel.panel-default
          .panel-body
            = simple_form_for [@field.section, @field], method: :put do |f|
              = render partial: 'fields/form', locals: { f: f }
              .form-group
                = f.button :button, class: 'btn-success' do
                  = sg 'pencil'
                  Update Field